export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const IS_LEAGUES = 'IS_LEAGUES';
export const FETCH_LEAGUES = 'FETCH_LEAGUES';
export const REQUEST_LEAGUES = 'REQUEST_LEAGUES';
export const FETCH_TEAMS = 'FETCH_TEAMS';
export const REQUEST_TEAMS = 'REQUEST_TEAMS';
export const GET_ERROR_MESSAGE = 'GET_ERROR_MESSAGE';
export const NULLIFY_ERROR_MESSAGE = 'NULLIFY_ERROR_MESSAGE';
export const GET_YEAR_SEASON = 'GET_YEAR_SEASON';
export const NULLIFY_YEAR_SEASON = 'NULLIFY_YEAR_SEASON';
export const GET_DATE_FROM_TO = 'GET_DATE_FROM_TO';
export const NULLIFY_DATE_FROM_TO = 'NULLIFY_DATE_FROM_TO';

